// NFe/SEFAZ integration structure
// This file provides the data models and structure for future SEFAZ integration
// No actual API calls to SEFAZ are made - this is preparation only

export interface NFeEmitente {
  cnpj: string
  ie: string
  razao_social: string
  nome_fantasia: string
  logradouro: string
  numero: string
  bairro: string
  municipio: string
  uf: string
  cep: string
  telefone: string
}

export interface NFeDestinatario {
  cpf_cnpj: string
  nome: string
  logradouro: string
  numero: string
  bairro: string
  municipio: string
  uf: string
  cep: string
  telefone: string
  email: string
}

export interface NFeItem {
  codigo: string
  descricao: string
  ncm: string
  cfop: string
  unidade: string
  quantidade: number
  valor_unitario: number
  valor_total: number
  icms_cst: string
  icms_aliquota: number
  pis_cst: string
  cofins_cst: string
}

export interface NFeData {
  emitente: NFeEmitente
  destinatario: NFeDestinatario
  items: NFeItem[]
  natureza_operacao: string
  valor_total: number
  modalidade_frete: number
  informacoes_complementares: string
  chave_acesso: string
  protocolo: string
  xml: string
}

// XML template builder - prepares the NFe XML structure
export function buildNFeXml(data: NFeData): string {
  // Return a well-formatted XML string following SEFAZ NFe schema
  // This is a template - actual XML will be generated by SEFAZ library
  return `<?xml version="1.0" encoding="UTF-8"?>
<nfeProc xmlns="http://www.portalfiscal.inf.br/nfe">
  <NFe>
    <infNFe>
      <ide>
        <cUF>29</cUF>
        <natOp>${data.natureza_operacao}</natOp>
        <mod>55</mod>
        <serie>1</serie>
        <nNF>1</nNF>
        <tpNF>1</tpNF>
        <tpEmis>1</tpEmis>
      </ide>
    </infNFe>
  </NFe>
</nfeProc>`
}

export function generateChaveAcesso(data: NFeData): string {
  // Placeholder for chave de acesso generation
  return "00000000000000000000000000000000000000000000"
}

export function validarNFe(data: NFeData): { valido: boolean; erros: string[] } {
  const erros: string[] = []
  if (!data.emitente.cnpj) erros.push("CNPJ do emitente é obrigatório")
  if (!data.emitente.razao_social) erros.push("Razão social do emitente é obrigatória")
  if (!data.destinatario.cpf_cnpj) erros.push("CPF/CNPJ do destinatário é obrigatório")
  if (!data.items.length) erros.push("Nenhum item na nota")
  if (!data.emitente.ie) erros.push("Inscrição estadual é obrigatória")
  return { valido: erros.length === 0, erros }
}
